# Generated by Django 3.1.2 on 2020-10-12 20:05

import classify.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(storage=classify.storage.OverwriteStorage(), upload_to='media/images'),
        ),
    ]
