# Generated by Django 3.1.2 on 2020-10-14 19:21

import classify.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0002_auto_20201012_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(storage=classify.storage.OverwriteStorage(), upload_to='images/'),
        ),
    ]
